# Generated by Django 4.2 on 2023-04-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='lichess_id',
            field=models.CharField(default='xxx', max_length=200),
            preserve_default=False,
        ),
    ]
