# Generated by Django 4.2 on 2023-04-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_lichess_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='lichess_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
