# Generated by Django 4.2 on 2024-05-07 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_season_end_date_season_start_date'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentteamresult',
            unique_together={('tournament', 'team')},
        ),
    ]
