# Generated by Django 4.2 on 2023-05-01 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_player_team_tournamentteamresults_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TournamentPlayerResults',
            new_name='TournamentPlayerResult',
        ),
        migrations.RenameModel(
            old_name='TournamentTeamResults',
            new_name='TournamentTeamResult',
        ),
        migrations.AddField(
            model_name='player',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
