# Generated by Django 4.2 on 2023-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_alter_tournamentplayerresult_nb_games'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamentplayerresult',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournamentplayerresult',
            name='score',
            field=models.FloatField(default=0),
        ),
    ]
