# Generated by Django 4.2 on 2023-09-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_player_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tournamentplayerresult',
            unique_together={('tournament', 'player')},
        ),
    ]
