# Generated by Django 4.2 on 2023-09-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_season_player_is_youngster_tournament_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
