# Generated by Django 4.2 on 2023-11-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_season_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
