# Generated by Django 4.2 on 2024-02-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_alter_player_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='current_season_players',
            field=models.TextField(blank=True, null=True),
        ),
    ]
