# Generated by Django 4.2 on 2024-03-02 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo_white', models.IntegerField(blank=True, null=True)),
                ('elo_black', models.IntegerField(blank=True, null=True)),
                ('elo_white_change', models.IntegerField(blank=True, null=True)),
                ('elo_black_change', models.IntegerField(blank=True, null=True)),
                ('result', models.CharField(blank=True, choices=[('1-0', '1-0'), ('0-1', '0-1'), ('1/2-1/2', '1/2-1/2')], max_length=200, null=True)),
                ('opening', models.CharField(blank=True, max_length=200, null=True)),
                ('moves', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True, unique=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_black', to='tournament.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_white', to='tournament.player')),
                ('team_black', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_black', to='tournament.team')),
                ('team_white', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_white', to='tournament.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
