# Generated by Django 4.2 on 2023-11-19 15:19

from django.db import migrations, models
import django.db.models.deletion
import game.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tournament', '0012_alter_player_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, choices=[(game.models.GameResult['black_win'], 'black_win'), (game.models.GameResult['white_win'], 'white_win'), (game.models.GameResult['draw'], 'draw')], max_length=200, null=True)),
                ('opening', models.CharField(blank=True, max_length=200, null=True)),
                ('moves', models.TextField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('player_black', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_black', to='tournament.player')),
                ('player_white', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_white', to='tournament.player')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
